### ISSUE TITLE
fourbfiveb in waveout.py

### ISSUE THREAD

**Issue by KOPACb** [ferdinandkeil/ADS129X#1]
Hello, i cant find library from your code ADS129X/examples/Serial_EMG/waveout.py  named fourbfiveb
$ python waveout.py 
Traceback (most recent call last):
  File "waveout.py", line 25, in <module>
    import fourbfiveb
ImportError: No module named fourbfiveb

gogle does not help me

**Comment by ferdinandkeil** [comment]
My mistake, forgot to add it to the repository. I've just added it in b92a617. You should now be able to run the script.
