### ISSUE TITLE
Upgrade: Teensy 3.6

### ISSUE THREAD

**Issue by andrewjaykeller** [ferdinandkeil/ADS129X#2]
Expected:

Use this library with a teensy 3.6 and ADS1299.

Problem:

This library is using outdated SPI calls

**Comment by ferdinandkeil** [comment]
Thank you for letting me know about this issue :+1: 

Is the code at least compiling?

**Comment by andrewjaykeller** [comment]
The code is compiling!

**Comment by ferdinandkeil** [comment]
Thanks for your help! I'll close this issue.
